# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carlos Morera de la Chica
name: Carlos Morera de la Chica 
email: carlos@codurance.com
location: London, UK
company: Codurance
company_link: www.codurance.com
github_url: https://github.com/carlosmchica
github_user: carlosmchica
twitter_url: https://twitter.com/CarlosMChica
twitter_user: carlosmchica
description: Software Craftsman Apprentice at Codurance
favicon: favicon.png # Image must be in assets/images
repository: carlosmchica/carlosmchica.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://carlosmchica.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults:
        - scope:
                path: "" # an empty string here means all files in the project
                type: "posts" # previously `post` in Jekyll 2.2.
          values:
                permalink: /:title/ #default post permalink 

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: carlosmchica.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  - href: /
    label: Home

  - href: /open-source
    label: Open-Source

  - href: /blog
    label: Blog

  - href: /about
    label: About


# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-81755706-1'

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C#, Software Craftsmanship, Clean Code, Software Design, DDD, TDD, Agile,  Design Patterns]
#skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, AngularJS, NodeJS, ExpressJS, MongoDB, Boostrap]
skill_mobile_app_keywords: [Android, Material Design]

